"""add_notification_settings_to_user

Revision ID: 085779c35702
Revises: 755f8edd327c
Create Date: 2026-08-10 12:27:23.273327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085779c35702'
down_revision: Union[str, Sequence[str], None] = '755f8edd327c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_new_tickets', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('notify_ticket_updates', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('notify_comments', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_comments')
        batch_op.drop_column('notify_ticket_updates')
        batch_op.drop_column('notify_new_tickets')

    # ### end Alembic commands ###
